# Generated by Codex on 2026-07-05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="provider",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("github", "Github"),
                    ("gitlab", "GitLab"),
                    ("dingtalk", "DingTalk"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="DingTalkDepartment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("corp_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("dept_id", models.CharField(db_index=True, max_length=255)),
                ("parent_dept_id", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "DingTalk Department",
                "verbose_name_plural": "DingTalk Departments",
                "db_table": "dingtalk_departments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DingTalkUser",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("corp_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("union_id", models.CharField(db_index=True, max_length=255)),
                ("open_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dingtalk_user_id",
                    models.CharField(blank=True, db_index=True, max_length=255, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("nick", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("avatar_url", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "last_synced_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dingtalk_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DingTalk User",
                "verbose_name_plural": "DingTalk Users",
                "db_table": "dingtalk_users",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DingTalkUserDepartment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="db.dingtalkdepartment",
                    ),
                ),
                (
                    "dingtalk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_links",
                        to="db.dingtalkuser",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "DingTalk User Department",
                "verbose_name_plural": "DingTalk User Departments",
                "db_table": "dingtalk_user_departments",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="dingtalkdepartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("corp_id", "dept_id"),
                name="dingtalk_department_unique_corp_dept_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="dingtalkuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("corp_id", "union_id"),
                name="dingtalk_user_unique_corp_union_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="dingtalkuserdepartment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("dingtalk_user", "department"),
                name="dingtalk_user_department_unique_user_dept_when_deleted_at_null",
            ),
        ),
    ]
